{
  "comments": [
    {
      "key": {
        "uuid": "1a106d94_24665551",
        "filename": "rdomanager_oscplugin/utils.py",
        "patchSetId": 13
      },
      "lineNbr": 323,
      "author": {
        "id": 1003910
      },
      "writtenOn": "2015-05-15T11:00:21Z",
      "side": 1,
      "message": "Can be a case, that known_hosts file does not exist? If yes, command fails (at least locally). But if it came from instack..",
      "range": {
        "startLine": 323,
        "startChar": 14,
        "endLine": 323,
        "endChar": 48
      },
      "revId": "16cfb546b8f114472c4f8aea16a7e6c308a1a9e6",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}